apiVersion: v1
kind: Secret
metadata:
  name: agrosolutions-ingest-secret
type: Opaque
stringData:
  Messaging__Username: guest
  Messaging__Password: guest
  Jwt__Secret: _5loyi91*1!o6imaof&n&!0l#6#mcn=p(!n9fe-zg8@c7zoi+y
  MongoDb__ConnectionString: mongodb://admin:Users!Passw0rd@agrosolutions-ingest-mongodb:27017
  InfluxDB__Password: "agrosolutionsAdmin123$"
  InfluxDB__Token: "Je2LUfYXX9o10pAcYgzsG8tWeRlR5qwKjpAqlV_sf-HyD09G2-eG90yyOXWa6tNVDtwKzq_zshT6XXd4FYBi3A=="
