apiVersion: v1
kind: ConfigMap
metadata:
  name: agrosolutions-ingest-config
data:
  ASPNETCORE_URLS: http://+:8080
  Messaging__Host: rabbitmq
  Messaging__Port: "5672"
  Messaging__Exchange: agro-solutions.exchange
  Messaging__Destinations__0__Id: RECEIVED_SENSOR_DATA
  Messaging__Destinations__0__Queue: received-sensor-data-to-influxdb
  Messaging__Destinations__0__RoutingKey: received.sensor.data
  Jwt__Issuer: AgroSolutions.Ingest
  Jwt__Audience: SensorsAgroSolutions
  MongoDb__Database: AgroSolutionsIngest
  InfluxDB__Url: http://agrosolutions-ingest-influxdb:8086
  InfluxDB__Username: agrosolutions-admin
  InfluxDB__Org: agrosolutions-org
  InfluxDB__Bucket: agrosolutions-bucket
  GrafanaLoki__Url: http://loki:3100
