name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Running the Compilation Job
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the source code
        uses: actions/checkout@v6

      - name: Download the .NET SDK
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: 10.0.x

      - name: Download the dependencies (dotnet restore)
        run: dotnet restore AgroSolutions.Ingest.slnx

      - name: Compile the application
        run: dotnet build AgroSolutions.Ingest.slnx

      - name: Execution of unit tests
        run: dotnet test AgroSolutions.Ingest.slnx
